# Labeler configuration
# See: https://github.com/actions/labeler
# Labels must match those defined in .github/maintenance/labels.sh

# Documentation
area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**/*"

# CI/CD
area/ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**/*"

# Configuration
area/config:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.toml"
          - "**/*.yaml"
          - "**/*.yml"
          - "!.github/**/*"

# Dependencies
area/deps:
  - changed-files:
      - any-glob-to-any-file:
          - "Cargo.toml"
          - "Cargo.lock"

# Testing
area/testing:
  - changed-files:
      - any-glob-to-any-file:
          - "**/tests/**/*"
          - "**/*_test.rs"
          - "**/*_tests.rs"

# API
area/api:
  - changed-files:
      - any-glob-to-any-file:
          - "src/commands/**/*"
          - "src/api/**/*"

# Authentication
area/auth:
  - changed-files:
      - any-glob-to-any-file:
          - "src/auth/**/*"
          - "src/credentials/**/*"
