//! Tailscale credential handling for dev commands.
//!
//! Manages loading, saving, and prompting for Tailscale OAuth credentials.

use std::{env, fs};

use super::{commands::run_command_optional, paths::get_tailscale_creds_file};
use crate::error::{Error, Result};

/// Load cached Tailscale credentials.
pub fn load_tailscale_credentials() -> Option<(String, String)> {
    let creds_file = get_tailscale_creds_file();
    if !creds_file.exists() {
        return None;
    }

    let content = fs::read_to_string(&creds_file).ok()?;
    let mut client_id = None;
    let mut client_secret = None;

    for line in content.lines() {
        let line = line.trim();
        if line.starts_with("TAILSCALE_CLIENT_ID=") {
            client_id =
                Some(line.trim_start_matches("TAILSCALE_CLIENT_ID=").trim_matches('"').to_string());
        } else if line.starts_with("TAILSCALE_CLIENT_SECRET=") {
            client_secret = Some(
                line.trim_start_matches("TAILSCALE_CLIENT_SECRET=").trim_matches('"').to_string(),
            );
        }
    }

    match (client_id, client_secret) {
        (Some(id), Some(secret)) if !id.is_empty() && !secret.is_empty() => Some((id, secret)),
        _ => None,
    }
}

/// Save Tailscale credentials.
pub fn save_tailscale_credentials(client_id: &str, client_secret: &str) -> Result<()> {
    let creds_file = get_tailscale_creds_file();
    if let Some(parent) = creds_file.parent() {
        fs::create_dir_all(parent)
            .map_err(|e| Error::Other(format!("Failed to create directory: {e}")))?;
    }

    let content = format!(
        "# Tailscale OAuth credentials for InferaDB development\n\
         # Generated by inferadb dev start\n\
         TAILSCALE_CLIENT_ID=\"{client_id}\"\n\
         TAILSCALE_CLIENT_SECRET=\"{client_secret}\"\n"
    );

    fs::write(&creds_file, &content)
        .map_err(|e| Error::Other(format!("Failed to write credentials: {e}")))?;

    // Set file permissions to 600 on Unix
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&creds_file)?.permissions();
        perms.set_mode(0o600);
        fs::set_permissions(&creds_file, perms)?;
    }

    println!("Credentials saved to {}", creds_file.display());
    Ok(())
}

/// Get Tailscale credentials from environment, cache, or prompt.
pub fn get_tailscale_credentials() -> Result<(String, String)> {
    use teapot::forms::{Field, Form, Group};

    // Try environment variables first
    if let (Ok(id), Ok(secret)) =
        (env::var("TAILSCALE_CLIENT_ID"), env::var("TAILSCALE_CLIENT_SECRET"))
        && !id.is_empty()
        && !secret.is_empty()
    {
        return Ok((id, secret));
    }

    // Try cached credentials
    if let Some((id, secret)) = load_tailscale_credentials() {
        return Ok((id, secret));
    }

    // Build the credentials form with setup instructions
    let instructions = r"Tailscale OAuth credentials are required for the Kubernetes operator.

Step 1: Enable HTTPS on your tailnet (one-time setup)
  Go to: https://login.tailscale.com/admin/dns
  Scroll to 'HTTPS Certificates' and click 'Enable HTTPS'

Step 2: Create tags (one-time setup)
  Go to: https://login.tailscale.com/admin/acls/tags
  Create tag 'k8s-operator' with yourself as owner
  Create tag 'k8s' with 'tag:k8s-operator' as owner

Step 3: Create OAuth client
  Go to: https://login.tailscale.com/admin/settings/oauth
  Click 'Generate OAuth client'
  Add scopes:
    - Devices → Core: Read & Write, tag: k8s-operator
    - Keys → Auth Keys: Read & Write, tag: k8s-operator
  Click 'Generate client' and copy the credentials";

    let form = Form::new().title("Tailscale Setup").group(
        Group::new()
            .field(Field::note().content(instructions).build())
            .field(Field::input().key("client_id").title("Client ID").required(true).build())
            .field(
                Field::input()
                    .key("client_secret")
                    .title("Client Secret")
                    .required(true)
                    .hidden(true)
                    .build(),
            ),
    );

    let results = crate::tui::run_form(form)?
        .ok_or_else(|| Error::Other("Credentials input cancelled".to_string()))?;

    let client_id = results
        .get_string("client_id")
        .ok_or_else(|| Error::Other("Client ID is required".to_string()))?
        .to_string();

    let client_secret = results
        .get_string("client_secret")
        .ok_or_else(|| Error::Other("Client Secret is required".to_string()))?
        .to_string();

    if client_id.is_empty() || client_secret.is_empty() {
        return Err(Error::Other("Both Client ID and Client Secret are required".to_string()));
    }

    // Save credentials for future use
    save_tailscale_credentials(&client_id, &client_secret)?;

    Ok((client_id, client_secret))
}

/// Get tailnet domain from local Tailscale CLI.
pub fn get_tailnet_info() -> Option<String> {
    let output = run_command_optional("tailscale", &["status", "--json"])?;

    // Extract DNS name from JSON (simple parsing)
    for line in output.lines() {
        if line.contains("\"DNSName\"") {
            // Extract domain from "DNSName": "hostname.tail27bf77.ts.net."
            if let Some(start) = line.find(".ts.net") {
                // Work backwards to find the tailnet part
                let before_ts = &line[..start];
                if let Some(dot_pos) = before_ts.rfind('.') {
                    let tailnet = &before_ts[dot_pos + 1..];
                    return Some(format!("{tailnet}.ts.net"));
                }
            }
        }
    }
    None
}
